http:
  host: "0.0.0.0"
  port: "8080"

pg:
  host: "postgres-staging"
  port: "55432"
  database: "staging"
  user: "admin"
  password: "staging_secret"
  sslmode: "require"

client:
  inventory_address: "0.0.0.0:50051"
  payment_address: "0.0.0.0:50052"
  iam_address: "0.0.0.0:50053"

kafka:
  brokers: [ "localhost:9092" ]

ship_assembled_consumer:
  topic_name: "assembly.ship-assembled"
  group: "order-service-ship-assembled-consumer"

order_paid_producer:
  topic_name: "order.paid"
