env:
  app_env: "development"
  service_name: "order-service"
  service_version: "1.0.0"

http:
  host: "localhost"
  port: "8080"

logger:
  level: "info"

pg:
  host: "localhost"
  port: "55432"
  database: "demo"
  user: "demo"
  password: "demo"
  sslmode: "disable"

client:
  inventory_address: "localhost:50051"
  payment_address: "localhost:50052"
  iam_address: "localhost:50053"

kafka:
  brokers: [ "localhost:9092" ]

ship_assembled_consumer:
  topic_name: "assembly.ship-assembled"
  group: "order-service-ship-assembled-consumer"

order_paid_producer:
  topic_name: "order.paid"

otel:
  endpoint: "localhost:4317"
  enable_otlp: true
  sampling_ratio: 1.0

rate_limit:
  redis_address: "localhost:6379"
  rate: 100
  burst: 200