http:
  host: "0.0.0.0"
  port: "8080"

pg:
  host: "postgres-staging"
  port: "55432"
  database: "ufo_staging"
  user: "ufo_admin"
  password: "staging_secret"
  sslmode: "require"

client:
  inventory_address: "0.0.0.0:50051"
  payment_address: "0.0.0.0:50052"