http:
  host: "0.0.0.0"
  port: "8080"

pg:
  host: "postgres-production"
  port: "55432"
  database: "ufo"
  user: "MUST_BE_SET_VIA_ENV"
  password: "MUST_BE_SET_VIA_ENV"
  sslmode: "require"

client:
  inventory_address: "0.0.0.0:50051"
  payment_address: "0.0.0.0:50052"

kafka:
  brokers: [ "localhost:9092" ]

ship_assembled_consumer:
  topic_name: "assembly.ship-assembled"
  group: "order-service-ship-assembled-consumer"

order_paid_producer:
  topic_name: "order.paid"
