// Code generated for rocket-factory service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vixart/rocket-factory/iam/internal/model"
	"github.com/vixart/rocket-factory/iam/internal/service/input"
)

// NewSessionService creates a new instance of SessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionService {
	mock := &SessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionService is an autogenerated mock type for the SessionService type
type SessionService struct {
	mock.Mock
}

type SessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionService) EXPECT() *SessionService_Expecter {
	return &SessionService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type SessionService
func (_mock *SessionService) Login(ctx context.Context, input1 input.UserLoginInput) (uuid.UUID, error) {
	ret := _mock.Called(ctx, input1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.UserLoginInput) (uuid.UUID, error)); ok {
		return returnFunc(ctx, input1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.UserLoginInput) uuid.UUID); ok {
		r0 = returnFunc(ctx, input1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.UserLoginInput) error); ok {
		r1 = returnFunc(ctx, input1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type SessionService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input1 input.UserLoginInput
func (_e *SessionService_Expecter) Login(ctx interface{}, input1 interface{}) *SessionService_Login_Call {
	return &SessionService_Login_Call{Call: _e.mock.On("Login", ctx, input1)}
}

func (_c *SessionService_Login_Call) Run(run func(ctx context.Context, input1 input.UserLoginInput)) *SessionService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.UserLoginInput
		if args[1] != nil {
			arg1 = args[1].(input.UserLoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionService_Login_Call) Return(uUID uuid.UUID, err error) *SessionService_Login_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *SessionService_Login_Call) RunAndReturn(run func(ctx context.Context, input1 input.UserLoginInput) (uuid.UUID, error)) *SessionService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type SessionService
func (_mock *SessionService) Logout(ctx context.Context, sessionUUID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type SessionService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID uuid.UUID
func (_e *SessionService_Expecter) Logout(ctx interface{}, sessionUUID interface{}) *SessionService_Logout_Call {
	return &SessionService_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionUUID)}
}

func (_c *SessionService_Logout_Call) Run(run func(ctx context.Context, sessionUUID uuid.UUID)) *SessionService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionService_Logout_Call) Return(err error) *SessionService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionService_Logout_Call) RunAndReturn(run func(ctx context.Context, sessionUUID uuid.UUID) error) *SessionService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Whoami provides a mock function for the type SessionService
func (_mock *SessionService) Whoami(ctx context.Context, sessionUUID uuid.UUID) (model.User, model.Session, error) {
	ret := _mock.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 model.User
	var r1 model.Session
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.User, model.Session, error)); ok {
		return returnFunc(ctx, sessionUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.User); ok {
		r0 = returnFunc(ctx, sessionUUID)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) model.Session); ok {
		r1 = returnFunc(ctx, sessionUUID)
	} else {
		r1 = ret.Get(1).(model.Session)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, sessionUUID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// SessionService_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type SessionService_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID uuid.UUID
func (_e *SessionService_Expecter) Whoami(ctx interface{}, sessionUUID interface{}) *SessionService_Whoami_Call {
	return &SessionService_Whoami_Call{Call: _e.mock.On("Whoami", ctx, sessionUUID)}
}

func (_c *SessionService_Whoami_Call) Run(run func(ctx context.Context, sessionUUID uuid.UUID)) *SessionService_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionService_Whoami_Call) Return(user model.User, session model.Session, err error) *SessionService_Whoami_Call {
	_c.Call.Return(user, session, err)
	return _c
}

func (_c *SessionService_Whoami_Call) RunAndReturn(run func(ctx context.Context, sessionUUID uuid.UUID) (model.User, model.Session, error)) *SessionService_Whoami_Call {
	_c.Call.Return(run)
	return _c
}
