// Code generated for rocket-factory service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vixart/rocket-factory/iam/internal/model"
)

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Delete(ctx context.Context, sessionUUID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID uuid.UUID
func (_e *SessionRepository_Expecter) Delete(ctx interface{}, sessionUUID interface{}) *SessionRepository_Delete_Call {
	return &SessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, sessionUUID)}
}

func (_c *SessionRepository_Delete_Call) Run(run func(ctx context.Context, sessionUUID uuid.UUID)) *SessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Delete_Call) Return(err error) *SessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, sessionUUID uuid.UUID) error) *SessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Get(ctx context.Context, sessionUuid uuid.UUID) (model.User, model.Session, error) {
	ret := _mock.Called(ctx, sessionUuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.User
	var r1 model.Session
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.User, model.Session, error)); ok {
		return returnFunc(ctx, sessionUuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.User); ok {
		r0 = returnFunc(ctx, sessionUuid)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) model.Session); ok {
		r1 = returnFunc(ctx, sessionUuid)
	} else {
		r1 = ret.Get(1).(model.Session)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, sessionUuid)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// SessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUuid uuid.UUID
func (_e *SessionRepository_Expecter) Get(ctx interface{}, sessionUuid interface{}) *SessionRepository_Get_Call {
	return &SessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, sessionUuid)}
}

func (_c *SessionRepository_Get_Call) Run(run func(ctx context.Context, sessionUuid uuid.UUID)) *SessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Get_Call) Return(user model.User, session model.Session, err error) *SessionRepository_Get_Call {
	_c.Call.Return(user, session, err)
	return _c
}

func (_c *SessionRepository_Get_Call) RunAndReturn(run func(ctx context.Context, sessionUuid uuid.UUID) (model.User, model.Session, error)) *SessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Set(ctx context.Context, sessionUUID uuid.UUID, user model.User, ttl time.Duration) error {
	ret := _mock.Called(ctx, sessionUUID, user, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.User, time.Duration) error); ok {
		r0 = returnFunc(ctx, sessionUUID, user, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type SessionRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID uuid.UUID
//   - user model.User
//   - ttl time.Duration
func (_e *SessionRepository_Expecter) Set(ctx interface{}, sessionUUID interface{}, user interface{}, ttl interface{}) *SessionRepository_Set_Call {
	return &SessionRepository_Set_Call{Call: _e.mock.On("Set", ctx, sessionUUID, user, ttl)}
}

func (_c *SessionRepository_Set_Call) Run(run func(ctx context.Context, sessionUUID uuid.UUID, user model.User, ttl time.Duration)) *SessionRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 model.User
		if args[2] != nil {
			arg2 = args[2].(model.User)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SessionRepository_Set_Call) Return(err error) *SessionRepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Set_Call) RunAndReturn(run func(ctx context.Context, sessionUUID uuid.UUID, user model.User, ttl time.Duration) error) *SessionRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}
