grpc:
  host: "localhost"
  port: "50051"

logger:
  level: "debug"

pg:
  host: "localhost"
  port: "55433"
  database: "demo"
  user: "demo"
  password: "demo"
  sslmode: "disable"

client:
  iam_address: "localhost:50053"
