env:
  app_env: "docker"
  service_name: "inventory-service"
  service_version: "1.0.0"

grpc:
  host: "0.0.0.0"
  port: "50051"

logger:
  level: "info"

pg:
  host: "postgres-inventory"
  port: "5432"
  database: "inventory-service"
  user: "inventory-service-user"
  password: "inventory-service-password"
  sslmode: "disable"

client:
  address: "iam-service:50053"

otel:
  endpoint: "otel-collector:4317"
  enable_otlp: true
  sampling_ratio: 1.0
