env:
  app_env: "development"
  service_name: "inventory-service"
  service_version: "1.0.0"

grpc:
  host: "localhost"
  port: "50051"

logger:
  level: "info"

pg:
  host: "localhost"
  port: "55433"
  database: "inventory-service"
  user: "inventory-service-user"
  password: "inventory-service-password"
  sslmode: "disable"

client:
  iam_address: "localhost:50053"

otel:
  endpoint: "localhost:4317"
  enable_otlp: true
  sampling_ratio: 1.0
