syntax = "proto3";

package payment.v1;

option go_package = "github.com/vixart/rocket-factory/shared/pkg/proto/payment/v1;paymentv1";

// PaymentService processes order payments
service PaymentService {
  // PayOrder processes the payment of an order
  rpc PayOrder(PayOrderRequest) returns (PayOrderResponse);
}

// Payment method
enum PaymentMethod {
  PAYMENT_METHOD_UNSPECIFIED = 0;
  PAYMENT_METHOD_CARD = 1;
  PAYMENT_METHOD_SBP = 2;
  PAYMENT_METHOD_CREDIT_CARD = 3;
  PAYMENT_METHOD_INVESTOR_MONEY = 4;
}

// Request to pay for an order
message PayOrderRequest {
  // Order UUID
  string order_uuid = 1;

  // Chosen payment method (required)
  PaymentMethod payment_method = 2;
}

// Order payment response
message PayOrderResponse {
  // Transaction UUID
  string transaction_uuid = 1;
}
