// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_GetPart_FullMethodName               = "/inventory.v1.InventoryService/GetPart"
	InventoryService_ListParts_FullMethodName             = "/inventory.v1.InventoryService/ListParts"
	InventoryService_ValidateCompatibility_FullMethodName = "/inventory.v1.InventoryService/ValidateCompatibility"
	InventoryService_ReserveParts_FullMethodName          = "/inventory.v1.InventoryService/ReserveParts"
	InventoryService_ReleaseParts_FullMethodName          = "/inventory.v1.InventoryService/ReleaseParts"
	InventoryService_CommitParts_FullMethodName           = "/inventory.v1.InventoryService/CommitParts"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryService управляет каталогом деталей для космических кораблей
type InventoryServiceClient interface {
	// GetPart возвращает деталь по UUID
	GetPart(ctx context.Context, in *GetPartRequest, opts ...grpc.CallOption) (*GetPartResponse, error)
	// ListParts возвращает список деталей с опциональной фильтрацией
	ListParts(ctx context.Context, in *ListPartsRequest, opts ...grpc.CallOption) (*ListPartsResponse, error)
	// ValidateCompatibility проверяет совместимость деталей между собой
	ValidateCompatibility(ctx context.Context, in *ValidateCompatibilityRequest, opts ...grpc.CallOption) (*ValidateCompatibilityResponse, error)
	// ReserveParts резервирует детали для заказа
	ReserveParts(ctx context.Context, in *ReservePartsRequest, opts ...grpc.CallOption) (*ReservePartsResponse, error)
	// ReleaseParts освобождает ранее зарезервированные детали
	ReleaseParts(ctx context.Context, in *ReleasePartsRequest, opts ...grpc.CallOption) (*ReleasePartsResponse, error)
	// CommitParts списывает детали со склада после успешной сборки корабля
	// Вызывается OrderService после получения события ShipAssembled из Kafka
	// stock -= 1, reserved -= 1 для каждой детали
	CommitParts(ctx context.Context, in *CommitPartsRequest, opts ...grpc.CallOption) (*CommitPartsResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) GetPart(ctx context.Context, in *GetPartRequest, opts ...grpc.CallOption) (*GetPartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListParts(ctx context.Context, in *ListPartsRequest, opts ...grpc.CallOption) (*ListPartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartsResponse)
	err := c.cc.Invoke(ctx, InventoryService_ListParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ValidateCompatibility(ctx context.Context, in *ValidateCompatibilityRequest, opts ...grpc.CallOption) (*ValidateCompatibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCompatibilityResponse)
	err := c.cc.Invoke(ctx, InventoryService_ValidateCompatibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReserveParts(ctx context.Context, in *ReservePartsRequest, opts ...grpc.CallOption) (*ReservePartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReservePartsResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReserveParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReleaseParts(ctx context.Context, in *ReleasePartsRequest, opts ...grpc.CallOption) (*ReleasePartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleasePartsResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReleaseParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CommitParts(ctx context.Context, in *CommitPartsRequest, opts ...grpc.CallOption) (*CommitPartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitPartsResponse)
	err := c.cc.Invoke(ctx, InventoryService_CommitParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
//
// InventoryService управляет каталогом деталей для космических кораблей
type InventoryServiceServer interface {
	// GetPart возвращает деталь по UUID
	GetPart(context.Context, *GetPartRequest) (*GetPartResponse, error)
	// ListParts возвращает список деталей с опциональной фильтрацией
	ListParts(context.Context, *ListPartsRequest) (*ListPartsResponse, error)
	// ValidateCompatibility проверяет совместимость деталей между собой
	ValidateCompatibility(context.Context, *ValidateCompatibilityRequest) (*ValidateCompatibilityResponse, error)
	// ReserveParts резервирует детали для заказа
	ReserveParts(context.Context, *ReservePartsRequest) (*ReservePartsResponse, error)
	// ReleaseParts освобождает ранее зарезервированные детали
	ReleaseParts(context.Context, *ReleasePartsRequest) (*ReleasePartsResponse, error)
	// CommitParts списывает детали со склада после успешной сборки корабля
	// Вызывается OrderService после получения события ShipAssembled из Kafka
	// stock -= 1, reserved -= 1 для каждой детали
	CommitParts(context.Context, *CommitPartsRequest) (*CommitPartsResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) GetPart(context.Context, *GetPartRequest) (*GetPartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPart not implemented")
}
func (UnimplementedInventoryServiceServer) ListParts(context.Context, *ListPartsRequest) (*ListPartsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListParts not implemented")
}
func (UnimplementedInventoryServiceServer) ValidateCompatibility(context.Context, *ValidateCompatibilityRequest) (*ValidateCompatibilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCompatibility not implemented")
}
func (UnimplementedInventoryServiceServer) ReserveParts(context.Context, *ReservePartsRequest) (*ReservePartsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveParts not implemented")
}
func (UnimplementedInventoryServiceServer) ReleaseParts(context.Context, *ReleasePartsRequest) (*ReleasePartsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseParts not implemented")
}
func (UnimplementedInventoryServiceServer) CommitParts(context.Context, *CommitPartsRequest) (*CommitPartsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitParts not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_GetPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetPart(ctx, req.(*GetPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListParts(ctx, req.(*ListPartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ValidateCompatibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCompatibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ValidateCompatibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ValidateCompatibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ValidateCompatibility(ctx, req.(*ValidateCompatibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReserveParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservePartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReserveParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReserveParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReserveParts(ctx, req.(*ReservePartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReleaseParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleasePartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReleaseParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReleaseParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReleaseParts(ctx, req.(*ReleasePartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CommitParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitPartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CommitParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CommitParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CommitParts(ctx, req.(*CommitPartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPart",
			Handler:    _InventoryService_GetPart_Handler,
		},
		{
			MethodName: "ListParts",
			Handler:    _InventoryService_ListParts_Handler,
		},
		{
			MethodName: "ValidateCompatibility",
			Handler:    _InventoryService_ValidateCompatibility_Handler,
		},
		{
			MethodName: "ReserveParts",
			Handler:    _InventoryService_ReserveParts_Handler,
		},
		{
			MethodName: "ReleaseParts",
			Handler:    _InventoryService_ReleaseParts_Handler,
		},
		{
			MethodName: "CommitParts",
			Handler:    _InventoryService_CommitParts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}
