// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Part type
type PartType int32

const (
	// Unspecified
	PartType_PART_TYPE_UNSPECIFIED PartType = 0
	// Hull
	PartType_PART_TYPE_HULL PartType = 1
	// Engine
	PartType_PART_TYPE_ENGINE PartType = 2
	// Shield
	PartType_PART_TYPE_SHIELD PartType = 3
	// Weapon
	PartType_PART_TYPE_WEAPON PartType = 4
)

// Enum value maps for PartType.
var (
	PartType_name = map[int32]string{
		0: "PART_TYPE_UNSPECIFIED",
		1: "PART_TYPE_HULL",
		2: "PART_TYPE_ENGINE",
		3: "PART_TYPE_SHIELD",
		4: "PART_TYPE_WEAPON",
	}
	PartType_value = map[string]int32{
		"PART_TYPE_UNSPECIFIED": 0,
		"PART_TYPE_HULL":        1,
		"PART_TYPE_ENGINE":      2,
		"PART_TYPE_SHIELD":      3,
		"PART_TYPE_WEAPON":      4,
	}
)

func (x PartType) Enum() *PartType {
	p := new(PartType)
	*p = x
	return p
}

func (x PartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartType) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (PartType) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[0]
}

func (x PartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartType.Descriptor instead.
func (PartType) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

// Part is a spaceship part
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique part identifier
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Part name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Part description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Price in kopecks (5000 RUB = 500000)
	Price int64 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	// Part type
	PartType PartType `protobuf:"varint,5,opt,name=part_type,json=partType,proto3,enum=inventory.v1.PartType" json:"part_type,omitempty"`
	// Quantity in stock
	StockQuantity int64 `protobuf:"varint,6,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	// Creation date
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Part) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Part) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Part) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Part) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Part) GetPartType() PartType {
	if x != nil {
		return x.PartType
	}
	return PartType_PART_TYPE_UNSPECIFIED
}

func (x *Part) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Part) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Request to fetch a part by UUID
type GetPartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Part UUID
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartRequest) Reset() {
	*x = GetPartRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartRequest) ProtoMessage() {}

func (x *GetPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartRequest.ProtoReflect.Descriptor instead.
func (*GetPartRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetPartRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Response carrying the part
type GetPartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The part that was found
	Part          *Part `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartResponse) Reset() {
	*x = GetPartResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartResponse) ProtoMessage() {}

func (x *GetPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartResponse.ProtoReflect.Descriptor instead.
func (*GetPartResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetPartResponse) GetPart() *Part {
	if x != nil {
		return x.Part
	}
	return nil
}

// Request to list parts
type ListPartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by part type
	PartType PartType `protobuf:"varint,1,opt,name=part_type,json=partType,proto3,enum=inventory.v1.PartType" json:"part_type,omitempty"`
	// Filter by UUID
	Uuids         []string `protobuf:"bytes,2,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsRequest) Reset() {
	*x = ListPartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsRequest) ProtoMessage() {}

func (x *ListPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsRequest.ProtoReflect.Descriptor instead.
func (*ListPartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ListPartsRequest) GetPartType() PartType {
	if x != nil {
		return x.PartType
	}
	return PartType_PART_TYPE_UNSPECIFIED
}

func (x *ListPartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

// Response carrying the list of parts
type ListPartsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parts
	Parts         []*Part `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsResponse) Reset() {
	*x = ListPartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsResponse) ProtoMessage() {}

func (x *ListPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsResponse.ProtoReflect.Descriptor instead.
func (*ListPartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ListPartsResponse) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

// Request to validate part compatibility across the ship slots
type ValidateCompatibilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of the part in the hull slot (required slot)
	HullUuid string `protobuf:"bytes,1,opt,name=hull_uuid,json=hullUuid,proto3" json:"hull_uuid,omitempty"`
	// UUID of the part in the engine slot (required slot)
	EngineUuid string `protobuf:"bytes,2,opt,name=engine_uuid,json=engineUuid,proto3" json:"engine_uuid,omitempty"`
	// UUID of the part in the shield slot (optional; an empty string means the slot is unused)
	ShieldUuid string `protobuf:"bytes,3,opt,name=shield_uuid,json=shieldUuid,proto3" json:"shield_uuid,omitempty"`
	// UUID of the part in the weapon slot (optional; an empty string means the slot is unused)
	WeaponUuid    string `protobuf:"bytes,4,opt,name=weapon_uuid,json=weaponUuid,proto3" json:"weapon_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCompatibilityRequest) Reset() {
	*x = ValidateCompatibilityRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCompatibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCompatibilityRequest) ProtoMessage() {}

func (x *ValidateCompatibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCompatibilityRequest.ProtoReflect.Descriptor instead.
func (*ValidateCompatibilityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateCompatibilityRequest) GetHullUuid() string {
	if x != nil {
		return x.HullUuid
	}
	return ""
}

func (x *ValidateCompatibilityRequest) GetEngineUuid() string {
	if x != nil {
		return x.EngineUuid
	}
	return ""
}

func (x *ValidateCompatibilityRequest) GetShieldUuid() string {
	if x != nil {
		return x.ShieldUuid
	}
	return ""
}

func (x *ValidateCompatibilityRequest) GetWeaponUuid() string {
	if x != nil {
		return x.WeaponUuid
	}
	return ""
}

// Compatibility response (empty means the parts are compatible)
type ValidateCompatibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCompatibilityResponse) Reset() {
	*x = ValidateCompatibilityResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCompatibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCompatibilityResponse) ProtoMessage() {}

func (x *ValidateCompatibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCompatibilityResponse.ProtoReflect.Descriptor instead.
func (*ValidateCompatibilityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

// Request to reserve parts
type ReservePartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDs of the parts to reserve
	Uuids         []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePartsRequest) Reset() {
	*x = ReservePartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePartsRequest) ProtoMessage() {}

func (x *ReservePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePartsRequest.ProtoReflect.Descriptor instead.
func (*ReservePartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ReservePartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

// Reservation response (empty means success)
type ReservePartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePartsResponse) Reset() {
	*x = ReservePartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePartsResponse) ProtoMessage() {}

func (x *ReservePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePartsResponse.ProtoReflect.Descriptor instead.
func (*ReservePartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

// Request to release previously reserved parts
type ReleasePartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDs of the parts to release
	Uuids         []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleasePartsRequest) Reset() {
	*x = ReleasePartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleasePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleasePartsRequest) ProtoMessage() {}

func (x *ReleasePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleasePartsRequest.ProtoReflect.Descriptor instead.
func (*ReleasePartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *ReleasePartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

// Release response (empty means success)
type ReleasePartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleasePartsResponse) Reset() {
	*x = ReleasePartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleasePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleasePartsResponse) ProtoMessage() {}

func (x *ReleasePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleasePartsResponse.ProtoReflect.Descriptor instead.
func (*ReleasePartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{10}
}

// Request to write parts off the stock
type CommitPartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDs of the parts to write off
	Uuids         []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPartsRequest) Reset() {
	*x = CommitPartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPartsRequest) ProtoMessage() {}

func (x *CommitPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPartsRequest.ProtoReflect.Descriptor instead.
func (*CommitPartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *CommitPartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

// Write-off response (empty means success)
type CommitPartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPartsResponse) Reset() {
	*x = CommitPartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPartsResponse) ProtoMessage() {}

func (x *CommitPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPartsResponse.ProtoReflect.Descriptor instead.
func (*CommitPartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{12}
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\x04Part\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x123\n" +
	"\tpart_type\x18\x05 \x01(\x0e2\x16.inventory.v1.PartTypeR\bpartType\x12%\n" +
	"\x0estock_quantity\x18\x06 \x01(\x03R\rstockQuantity\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"$\n" +
	"\x0eGetPartRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"9\n" +
	"\x0fGetPartResponse\x12&\n" +
	"\x04part\x18\x01 \x01(\v2\x12.inventory.v1.PartR\x04part\"]\n" +
	"\x10ListPartsRequest\x123\n" +
	"\tpart_type\x18\x01 \x01(\x0e2\x16.inventory.v1.PartTypeR\bpartType\x12\x14\n" +
	"\x05uuids\x18\x02 \x03(\tR\x05uuids\"=\n" +
	"\x11ListPartsResponse\x12(\n" +
	"\x05parts\x18\x01 \x03(\v2\x12.inventory.v1.PartR\x05parts\"\x9e\x01\n" +
	"\x1cValidateCompatibilityRequest\x12\x1b\n" +
	"\thull_uuid\x18\x01 \x01(\tR\bhullUuid\x12\x1f\n" +
	"\vengine_uuid\x18\x02 \x01(\tR\n" +
	"engineUuid\x12\x1f\n" +
	"\vshield_uuid\x18\x03 \x01(\tR\n" +
	"shieldUuid\x12\x1f\n" +
	"\vweapon_uuid\x18\x04 \x01(\tR\n" +
	"weaponUuid\"\x1f\n" +
	"\x1dValidateCompatibilityResponse\"+\n" +
	"\x13ReservePartsRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\"\x16\n" +
	"\x14ReservePartsResponse\"+\n" +
	"\x13ReleasePartsRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\"\x16\n" +
	"\x14ReleasePartsResponse\"*\n" +
	"\x12CommitPartsRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\"\x15\n" +
	"\x13CommitPartsResponse*{\n" +
	"\bPartType\x12\x19\n" +
	"\x15PART_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePART_TYPE_HULL\x10\x01\x12\x14\n" +
	"\x10PART_TYPE_ENGINE\x10\x02\x12\x14\n" +
	"\x10PART_TYPE_SHIELD\x10\x03\x12\x14\n" +
	"\x10PART_TYPE_WEAPON\x10\x042\x9c\x04\n" +
	"\x10InventoryService\x12F\n" +
	"\aGetPart\x12\x1c.inventory.v1.GetPartRequest\x1a\x1d.inventory.v1.GetPartResponse\x12L\n" +
	"\tListParts\x12\x1e.inventory.v1.ListPartsRequest\x1a\x1f.inventory.v1.ListPartsResponse\x12p\n" +
	"\x15ValidateCompatibility\x12*.inventory.v1.ValidateCompatibilityRequest\x1a+.inventory.v1.ValidateCompatibilityResponse\x12U\n" +
	"\fReserveParts\x12!.inventory.v1.ReservePartsRequest\x1a\".inventory.v1.ReservePartsResponse\x12U\n" +
	"\fReleaseParts\x12!.inventory.v1.ReleasePartsRequest\x1a\".inventory.v1.ReleasePartsResponse\x12R\n" +
	"\vCommitParts\x12 .inventory.v1.CommitPartsRequest\x1a!.inventory.v1.CommitPartsResponseBLZJgithub.com/vixart/rocket-factory/shared/pkg/proto/inventory/v1;inventoryv1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(PartType)(0),                         // 0: inventory.v1.PartType
	(*Part)(nil),                          // 1: inventory.v1.Part
	(*GetPartRequest)(nil),                // 2: inventory.v1.GetPartRequest
	(*GetPartResponse)(nil),               // 3: inventory.v1.GetPartResponse
	(*ListPartsRequest)(nil),              // 4: inventory.v1.ListPartsRequest
	(*ListPartsResponse)(nil),             // 5: inventory.v1.ListPartsResponse
	(*ValidateCompatibilityRequest)(nil),  // 6: inventory.v1.ValidateCompatibilityRequest
	(*ValidateCompatibilityResponse)(nil), // 7: inventory.v1.ValidateCompatibilityResponse
	(*ReservePartsRequest)(nil),           // 8: inventory.v1.ReservePartsRequest
	(*ReservePartsResponse)(nil),          // 9: inventory.v1.ReservePartsResponse
	(*ReleasePartsRequest)(nil),           // 10: inventory.v1.ReleasePartsRequest
	(*ReleasePartsResponse)(nil),          // 11: inventory.v1.ReleasePartsResponse
	(*CommitPartsRequest)(nil),            // 12: inventory.v1.CommitPartsRequest
	(*CommitPartsResponse)(nil),           // 13: inventory.v1.CommitPartsResponse
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.v1.Part.part_type:type_name -> inventory.v1.PartType
	14, // 1: inventory.v1.Part.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: inventory.v1.GetPartResponse.part:type_name -> inventory.v1.Part
	0,  // 3: inventory.v1.ListPartsRequest.part_type:type_name -> inventory.v1.PartType
	1,  // 4: inventory.v1.ListPartsResponse.parts:type_name -> inventory.v1.Part
	2,  // 5: inventory.v1.InventoryService.GetPart:input_type -> inventory.v1.GetPartRequest
	4,  // 6: inventory.v1.InventoryService.ListParts:input_type -> inventory.v1.ListPartsRequest
	6,  // 7: inventory.v1.InventoryService.ValidateCompatibility:input_type -> inventory.v1.ValidateCompatibilityRequest
	8,  // 8: inventory.v1.InventoryService.ReserveParts:input_type -> inventory.v1.ReservePartsRequest
	10, // 9: inventory.v1.InventoryService.ReleaseParts:input_type -> inventory.v1.ReleasePartsRequest
	12, // 10: inventory.v1.InventoryService.CommitParts:input_type -> inventory.v1.CommitPartsRequest
	3,  // 11: inventory.v1.InventoryService.GetPart:output_type -> inventory.v1.GetPartResponse
	5,  // 12: inventory.v1.InventoryService.ListParts:output_type -> inventory.v1.ListPartsResponse
	7,  // 13: inventory.v1.InventoryService.ValidateCompatibility:output_type -> inventory.v1.ValidateCompatibilityResponse
	9,  // 14: inventory.v1.InventoryService.ReserveParts:output_type -> inventory.v1.ReservePartsResponse
	11, // 15: inventory.v1.InventoryService.ReleaseParts:output_type -> inventory.v1.ReleasePartsResponse
	13, // 16: inventory.v1.InventoryService.CommitParts:output_type -> inventory.v1.CommitPartsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
