// Code generated for rocket-factory service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vixart/rocket-factory/iam/internal/model"
	"github.com/vixart/rocket-factory/iam/internal/service/input"
)

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type UserService
func (_mock *UserService) GetUser(ctx context.Context, userUuid uuid.UUID) (model.User, error) {
	ret := _mock.Called(ctx, userUuid)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.User, error)); ok {
		return returnFunc(ctx, userUuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.User); ok {
		r0 = returnFunc(ctx, userUuid)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userUuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userUuid uuid.UUID
func (_e *UserService_Expecter) GetUser(ctx interface{}, userUuid interface{}) *UserService_GetUser_Call {
	return &UserService_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userUuid)}
}

func (_c *UserService_GetUser_Call) Run(run func(ctx context.Context, userUuid uuid.UUID)) *UserService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_GetUser_Call) Return(user model.User, err error) *UserService_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserService_GetUser_Call) RunAndReturn(run func(ctx context.Context, userUuid uuid.UUID) (model.User, error)) *UserService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type UserService
func (_mock *UserService) Register(ctx context.Context, input1 input.UserRegisterInput) (model.User, error) {
	ret := _mock.Called(ctx, input1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.UserRegisterInput) (model.User, error)); ok {
		return returnFunc(ctx, input1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.UserRegisterInput) model.User); ok {
		r0 = returnFunc(ctx, input1)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.UserRegisterInput) error); ok {
		r1 = returnFunc(ctx, input1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type UserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - input1 input.UserRegisterInput
func (_e *UserService_Expecter) Register(ctx interface{}, input1 interface{}) *UserService_Register_Call {
	return &UserService_Register_Call{Call: _e.mock.On("Register", ctx, input1)}
}

func (_c *UserService_Register_Call) Run(run func(ctx context.Context, input1 input.UserRegisterInput)) *UserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.UserRegisterInput
		if args[1] != nil {
			arg1 = args[1].(input.UserRegisterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_Register_Call) Return(user model.User, err error) *UserService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserService_Register_Call) RunAndReturn(run func(ctx context.Context, input1 input.UserRegisterInput) (model.User, error)) *UserService_Register_Call {
	_c.Call.Return(run)
	return _c
}
