// Code generated for student service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vixart/rocket-factory/assembly/internal/model"
)

// NewShipAssembledProducer creates a new instance of ShipAssembledProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipAssembledProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipAssembledProducer {
	mock := &ShipAssembledProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipAssembledProducer is an autogenerated mock type for the ShipAssembledProducer type
type ShipAssembledProducer struct {
	mock.Mock
}

type ShipAssembledProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipAssembledProducer) EXPECT() *ShipAssembledProducer_Expecter {
	return &ShipAssembledProducer_Expecter{mock: &_m.Mock}
}

// ProduceShipAssembled provides a mock function for the type ShipAssembledProducer
func (_mock *ShipAssembledProducer) ProduceShipAssembled(ctx context.Context, event model.ShipAssembledEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceShipAssembled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShipAssembledEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ShipAssembledProducer_ProduceShipAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceShipAssembled'
type ShipAssembledProducer_ProduceShipAssembled_Call struct {
	*mock.Call
}

// ProduceShipAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledEvent
func (_e *ShipAssembledProducer_Expecter) ProduceShipAssembled(ctx interface{}, event interface{}) *ShipAssembledProducer_ProduceShipAssembled_Call {
	return &ShipAssembledProducer_ProduceShipAssembled_Call{Call: _e.mock.On("ProduceShipAssembled", ctx, event)}
}

func (_c *ShipAssembledProducer_ProduceShipAssembled_Call) Run(run func(ctx context.Context, event model.ShipAssembledEvent)) *ShipAssembledProducer_ProduceShipAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShipAssembledEvent
		if args[1] != nil {
			arg1 = args[1].(model.ShipAssembledEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShipAssembledProducer_ProduceShipAssembled_Call) Return(err error) *ShipAssembledProducer_ProduceShipAssembled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ShipAssembledProducer_ProduceShipAssembled_Call) RunAndReturn(run func(ctx context.Context, event model.ShipAssembledEvent) error) *ShipAssembledProducer_ProduceShipAssembled_Call {
	_c.Call.Return(run)
	return _c
}
