// Code generated for rocket-factory service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vixart/rocket-factory/platform/pkg/kafka"
)

// NewKafkaProducer creates a new instance of KafkaProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafkaProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *KafkaProducer {
	mock := &KafkaProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KafkaProducer is an autogenerated mock type for the KafkaProducer type
type KafkaProducer struct {
	mock.Mock
}

type KafkaProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *KafkaProducer) EXPECT() *KafkaProducer_Expecter {
	return &KafkaProducer_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type KafkaProducer
func (_mock *KafkaProducer) Send(ctx context.Context, msg *kafka.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KafkaProducer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type KafkaProducer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *kafka.Message
func (_e *KafkaProducer_Expecter) Send(ctx interface{}, msg interface{}) *KafkaProducer_Send_Call {
	return &KafkaProducer_Send_Call{Call: _e.mock.On("Send", ctx, msg)}
}

func (_c *KafkaProducer_Send_Call) Run(run func(ctx context.Context, msg *kafka.Message)) *KafkaProducer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kafka.Message
		if args[1] != nil {
			arg1 = args[1].(*kafka.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KafkaProducer_Send_Call) Return(err error) *KafkaProducer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KafkaProducer_Send_Call) RunAndReturn(run func(ctx context.Context, msg *kafka.Message) error) *KafkaProducer_Send_Call {
	_c.Call.Return(run)
	return _c
}
