// Code generated for student service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vixart/rocket-factory/payment/internal/model"
)

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

type PaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentService) EXPECT() *PaymentService_Expecter {
	return &PaymentService_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type PaymentService
func (_mock *PaymentService) PayOrder(context1 context.Context, orderUuid uuid.UUID, paymentMethod model.PaymentMethod) (*uuid.UUID, error) {
	ret := _mock.Called(context1, orderUuid, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.PaymentMethod) (*uuid.UUID, error)); ok {
		return returnFunc(context1, orderUuid, paymentMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.PaymentMethod) *uuid.UUID); ok {
		r0 = returnFunc(context1, orderUuid, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.PaymentMethod) error); ok {
		r1 = returnFunc(context1, orderUuid, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - context1 context.Context
//   - orderUuid uuid.UUID
//   - paymentMethod model.PaymentMethod
func (_e *PaymentService_Expecter) PayOrder(context1 interface{}, orderUuid interface{}, paymentMethod interface{}) *PaymentService_PayOrder_Call {
	return &PaymentService_PayOrder_Call{Call: _e.mock.On("PayOrder", context1, orderUuid, paymentMethod)}
}

func (_c *PaymentService_PayOrder_Call) Run(run func(context1 context.Context, orderUuid uuid.UUID, paymentMethod model.PaymentMethod)) *PaymentService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 model.PaymentMethod
		if args[2] != nil {
			arg2 = args[2].(model.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PaymentService_PayOrder_Call) Return(uUID *uuid.UUID, err error) *PaymentService_PayOrder_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *PaymentService_PayOrder_Call) RunAndReturn(run func(context1 context.Context, orderUuid uuid.UUID, paymentMethod model.PaymentMethod) (*uuid.UUID, error)) *PaymentService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
