// Code generated for student service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/vixart/rocket-factory/inventory/internal/model/entity"
)

// NewCompatibilityChecker creates a new instance of CompatibilityChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompatibilityChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompatibilityChecker {
	mock := &CompatibilityChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CompatibilityChecker is an autogenerated mock type for the CompatibilityChecker type
type CompatibilityChecker struct {
	mock.Mock
}

type CompatibilityChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *CompatibilityChecker) EXPECT() *CompatibilityChecker_Expecter {
	return &CompatibilityChecker_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type CompatibilityChecker
func (_mock *CompatibilityChecker) Check(parts entity.ResolvedShipSlots) error {
	ret := _mock.Called(parts)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(entity.ResolvedShipSlots) error); ok {
		r0 = returnFunc(parts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CompatibilityChecker_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type CompatibilityChecker_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - parts entity.ResolvedShipSlots
func (_e *CompatibilityChecker_Expecter) Check(parts interface{}) *CompatibilityChecker_Check_Call {
	return &CompatibilityChecker_Check_Call{Call: _e.mock.On("Check", parts)}
}

func (_c *CompatibilityChecker_Check_Call) Run(run func(parts entity.ResolvedShipSlots)) *CompatibilityChecker_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entity.ResolvedShipSlots
		if args[0] != nil {
			arg0 = args[0].(entity.ResolvedShipSlots)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CompatibilityChecker_Check_Call) Return(err error) *CompatibilityChecker_Check_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CompatibilityChecker_Check_Call) RunAndReturn(run func(parts entity.ResolvedShipSlots) error) *CompatibilityChecker_Check_Call {
	_c.Call.Return(run)
	return _c
}
