// Code generated for student service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vixart/rocket-factory/inventory/internal/model/entity"
	"github.com/vixart/rocket-factory/inventory/internal/service/input"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type Repository
func (_mock *Repository) Get(ctx context.Context, uuid1 uuid.UUID) (entity.Part, error) {
	ret := _mock.Called(ctx, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Part, error)); ok {
		return returnFunc(ctx, uuid1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Part); ok {
		r0 = returnFunc(ctx, uuid1)
	} else {
		r0 = ret.Get(0).(entity.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uuid1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
func (_e *Repository_Expecter) Get(ctx interface{}, uuid1 interface{}) *Repository_Get_Call {
	return &Repository_Get_Call{Call: _e.mock.On("Get", ctx, uuid1)}
}

func (_c *Repository_Get_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID)) *Repository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Get_Call) Return(part entity.Part, err error) *Repository_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *Repository_Get_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID) (entity.Part, error)) *Repository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type Repository
func (_mock *Repository) List(context1 context.Context, partFilter input.PartFilter) ([]entity.Part, error) {
	ret := _mock.Called(context1, partFilter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.PartFilter) ([]entity.Part, error)); ok {
		return returnFunc(context1, partFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.PartFilter) []entity.Part); ok {
		r0 = returnFunc(context1, partFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.PartFilter) error); ok {
		r1 = returnFunc(context1, partFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - partFilter input.PartFilter
func (_e *Repository_Expecter) List(context1 interface{}, partFilter interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", context1, partFilter)}
}

func (_c *Repository_List_Call) Run(run func(context1 context.Context, partFilter input.PartFilter)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.PartFilter
		if args[1] != nil {
			arg1 = args[1].(input.PartFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_List_Call) Return(parts []entity.Part, err error) *Repository_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(context1 context.Context, partFilter input.PartFilter) ([]entity.Part, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReservedBatch provides a mock function for the type Repository
func (_mock *Repository) UpdateReservedBatch(ctx context.Context, parts []entity.Part) error {
	ret := _mock.Called(ctx, parts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservedBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.Part) error); ok {
		r0 = returnFunc(ctx, parts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpdateReservedBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReservedBatch'
type Repository_UpdateReservedBatch_Call struct {
	*mock.Call
}

// UpdateReservedBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - parts []entity.Part
func (_e *Repository_Expecter) UpdateReservedBatch(ctx interface{}, parts interface{}) *Repository_UpdateReservedBatch_Call {
	return &Repository_UpdateReservedBatch_Call{Call: _e.mock.On("UpdateReservedBatch", ctx, parts)}
}

func (_c *Repository_UpdateReservedBatch_Call) Run(run func(ctx context.Context, parts []entity.Part)) *Repository_UpdateReservedBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entity.Part
		if args[1] != nil {
			arg1 = args[1].([]entity.Part)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_UpdateReservedBatch_Call) Return(err error) *Repository_UpdateReservedBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpdateReservedBatch_Call) RunAndReturn(run func(ctx context.Context, parts []entity.Part) error) *Repository_UpdateReservedBatch_Call {
	_c.Call.Return(run)
	return _c
}
