// Code generated for rocket-factory service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vixart/rocket-factory/platform/pkg/kafka"
)

// NewConsumer creates a new instance of Consumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Consumer {
	mock := &Consumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

type Consumer_Expecter struct {
	mock *mock.Mock
}

func (_m *Consumer) EXPECT() *Consumer_Expecter {
	return &Consumer_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type Consumer
func (_mock *Consumer) Consume(ctx context.Context, handler kafka.MessageHandler) error {
	ret := _mock.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kafka.MessageHandler) error); ok {
		r0 = returnFunc(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Consumer_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type Consumer_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - handler kafka.MessageHandler
func (_e *Consumer_Expecter) Consume(ctx interface{}, handler interface{}) *Consumer_Consume_Call {
	return &Consumer_Consume_Call{Call: _e.mock.On("Consume", ctx, handler)}
}

func (_c *Consumer_Consume_Call) Run(run func(ctx context.Context, handler kafka.MessageHandler)) *Consumer_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kafka.MessageHandler
		if args[1] != nil {
			arg1 = args[1].(kafka.MessageHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_Consume_Call) Return(err error) *Consumer_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Consumer_Consume_Call) RunAndReturn(run func(ctx context.Context, handler kafka.MessageHandler) error) *Consumer_Consume_Call {
	_c.Call.Return(run)
	return _c
}
