// Code generated for rocket-factory service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewShipAssembleService creates a new instance of ShipAssembleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipAssembleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipAssembleService {
	mock := &ShipAssembleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipAssembleService is an autogenerated mock type for the ShipAssembleService type
type ShipAssembleService struct {
	mock.Mock
}

type ShipAssembleService_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipAssembleService) EXPECT() *ShipAssembleService_Expecter {
	return &ShipAssembleService_Expecter{mock: &_m.Mock}
}

// Assemble provides a mock function for the type ShipAssembleService
func (_mock *ShipAssembleService) Assemble(ctx context.Context, orderUUID uuid.UUID, userUUID uuid.UUID) error {
	ret := _mock.Called(ctx, orderUUID, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for Assemble")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderUUID, userUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ShipAssembleService_Assemble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assemble'
type ShipAssembleService_Assemble_Call struct {
	*mock.Call
}

// Assemble is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
//   - userUUID uuid.UUID
func (_e *ShipAssembleService_Expecter) Assemble(ctx interface{}, orderUUID interface{}, userUUID interface{}) *ShipAssembleService_Assemble_Call {
	return &ShipAssembleService_Assemble_Call{Call: _e.mock.On("Assemble", ctx, orderUUID, userUUID)}
}

func (_c *ShipAssembleService_Assemble_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID, userUUID uuid.UUID)) *ShipAssembleService_Assemble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShipAssembleService_Assemble_Call) Return(err error) *ShipAssembleService_Assemble_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ShipAssembleService_Assemble_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID, userUUID uuid.UUID) error) *ShipAssembleService_Assemble_Call {
	_c.Call.Return(run)
	return _c
}
