// Code generated for rocket-factory service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTxManager creates a new instance of TxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxManager {
	mock := &TxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TxManager is an autogenerated mock type for the TxManager type
type TxManager struct {
	mock.Mock
}

type TxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TxManager) EXPECT() *TxManager_Expecter {
	return &TxManager_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type TxManager
func (_mock *TxManager) Do(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TxManager_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type TxManager_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *TxManager_Expecter) Do(ctx interface{}, fn interface{}) *TxManager_Do_Call {
	return &TxManager_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *TxManager_Do_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *TxManager_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TxManager_Do_Call) Return(err error) *TxManager_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TxManager_Do_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *TxManager_Do_Call {
	_c.Call.Return(run)
	return _c
}
