// Code generated for student service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vixart/rocket-factory/order/internal/model"
	"github.com/vixart/rocket-factory/order/internal/service/input"
)

// NewInventoryClient creates a new instance of InventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InventoryClient is an autogenerated mock type for the InventoryClient type
type InventoryClient struct {
	mock.Mock
}

type InventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryClient) EXPECT() *InventoryClient_Expecter {
	return &InventoryClient_Expecter{mock: &_m.Mock}
}

// CommitParts provides a mock function for the type InventoryClient
func (_mock *InventoryClient) CommitParts(ctx context.Context, uuids []uuid.UUID) error {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for CommitParts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InventoryClient_CommitParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitParts'
type InventoryClient_CommitParts_Call struct {
	*mock.Call
}

// CommitParts is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []uuid.UUID
func (_e *InventoryClient_Expecter) CommitParts(ctx interface{}, uuids interface{}) *InventoryClient_CommitParts_Call {
	return &InventoryClient_CommitParts_Call{Call: _e.mock.On("CommitParts", ctx, uuids)}
}

func (_c *InventoryClient_CommitParts_Call) Run(run func(ctx context.Context, uuids []uuid.UUID)) *InventoryClient_CommitParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryClient_CommitParts_Call) Return(err error) *InventoryClient_CommitParts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InventoryClient_CommitParts_Call) RunAndReturn(run func(ctx context.Context, uuids []uuid.UUID) error) *InventoryClient_CommitParts_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type InventoryClient
func (_mock *InventoryClient) ListParts(ctx context.Context, uuids []uuid.UUID) ([]model.Part, error) {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]model.Part, error)); ok {
		return returnFunc(ctx, uuids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []model.Part); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uuids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryClient_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryClient_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []uuid.UUID
func (_e *InventoryClient_Expecter) ListParts(ctx interface{}, uuids interface{}) *InventoryClient_ListParts_Call {
	return &InventoryClient_ListParts_Call{Call: _e.mock.On("ListParts", ctx, uuids)}
}

func (_c *InventoryClient_ListParts_Call) Run(run func(ctx context.Context, uuids []uuid.UUID)) *InventoryClient_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryClient_ListParts_Call) Return(parts []model.Part, err error) *InventoryClient_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *InventoryClient_ListParts_Call) RunAndReturn(run func(ctx context.Context, uuids []uuid.UUID) ([]model.Part, error)) *InventoryClient_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseParts provides a mock function for the type InventoryClient
func (_mock *InventoryClient) ReleaseParts(ctx context.Context, uuids []uuid.UUID) error {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseParts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InventoryClient_ReleaseParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseParts'
type InventoryClient_ReleaseParts_Call struct {
	*mock.Call
}

// ReleaseParts is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []uuid.UUID
func (_e *InventoryClient_Expecter) ReleaseParts(ctx interface{}, uuids interface{}) *InventoryClient_ReleaseParts_Call {
	return &InventoryClient_ReleaseParts_Call{Call: _e.mock.On("ReleaseParts", ctx, uuids)}
}

func (_c *InventoryClient_ReleaseParts_Call) Run(run func(ctx context.Context, uuids []uuid.UUID)) *InventoryClient_ReleaseParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryClient_ReleaseParts_Call) Return(err error) *InventoryClient_ReleaseParts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InventoryClient_ReleaseParts_Call) RunAndReturn(run func(ctx context.Context, uuids []uuid.UUID) error) *InventoryClient_ReleaseParts_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveParts provides a mock function for the type InventoryClient
func (_mock *InventoryClient) ReserveParts(ctx context.Context, uuids []uuid.UUID) error {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for ReserveParts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InventoryClient_ReserveParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveParts'
type InventoryClient_ReserveParts_Call struct {
	*mock.Call
}

// ReserveParts is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []uuid.UUID
func (_e *InventoryClient_Expecter) ReserveParts(ctx interface{}, uuids interface{}) *InventoryClient_ReserveParts_Call {
	return &InventoryClient_ReserveParts_Call{Call: _e.mock.On("ReserveParts", ctx, uuids)}
}

func (_c *InventoryClient_ReserveParts_Call) Run(run func(ctx context.Context, uuids []uuid.UUID)) *InventoryClient_ReserveParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryClient_ReserveParts_Call) Return(err error) *InventoryClient_ReserveParts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InventoryClient_ReserveParts_Call) RunAndReturn(run func(ctx context.Context, uuids []uuid.UUID) error) *InventoryClient_ReserveParts_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCompatibility provides a mock function for the type InventoryClient
func (_mock *InventoryClient) ValidateCompatibility(ctx context.Context, orderParts input.OrderParts) error {
	ret := _mock.Called(ctx, orderParts)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCompatibility")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.OrderParts) error); ok {
		r0 = returnFunc(ctx, orderParts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InventoryClient_ValidateCompatibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCompatibility'
type InventoryClient_ValidateCompatibility_Call struct {
	*mock.Call
}

// ValidateCompatibility is a helper method to define mock.On call
//   - ctx context.Context
//   - orderParts input.OrderParts
func (_e *InventoryClient_Expecter) ValidateCompatibility(ctx interface{}, orderParts interface{}) *InventoryClient_ValidateCompatibility_Call {
	return &InventoryClient_ValidateCompatibility_Call{Call: _e.mock.On("ValidateCompatibility", ctx, orderParts)}
}

func (_c *InventoryClient_ValidateCompatibility_Call) Run(run func(ctx context.Context, orderParts input.OrderParts)) *InventoryClient_ValidateCompatibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.OrderParts
		if args[1] != nil {
			arg1 = args[1].(input.OrderParts)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryClient_ValidateCompatibility_Call) Return(err error) *InventoryClient_ValidateCompatibility_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InventoryClient_ValidateCompatibility_Call) RunAndReturn(run func(ctx context.Context, orderParts input.OrderParts) error) *InventoryClient_ValidateCompatibility_Call {
	_c.Call.Return(run)
	return _c
}
