// Code generated for student service
// © Alex Mosh 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewIAMClient creates a new instance of IAMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAMClient {
	mock := &IAMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IAMClient is an autogenerated mock type for the IAMClient type
type IAMClient struct {
	mock.Mock
}

type IAMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IAMClient) EXPECT() *IAMClient_Expecter {
	return &IAMClient_Expecter{mock: &_m.Mock}
}

// Whoami provides a mock function for the type IAMClient
func (_mock *IAMClient) Whoami(ctx context.Context, sessionUUID uuid.UUID) (uuid.UUID, uuid.UUID, error) {
	ret := _mock.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 uuid.UUID
	var r1 uuid.UUID
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, uuid.UUID, error)); ok {
		return returnFunc(ctx, sessionUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, sessionUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r1 = returnFunc(ctx, sessionUUID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, sessionUUID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// IAMClient_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type IAMClient_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID uuid.UUID
func (_e *IAMClient_Expecter) Whoami(ctx interface{}, sessionUUID interface{}) *IAMClient_Whoami_Call {
	return &IAMClient_Whoami_Call{Call: _e.mock.On("Whoami", ctx, sessionUUID)}
}

func (_c *IAMClient_Whoami_Call) Run(run func(ctx context.Context, sessionUUID uuid.UUID)) *IAMClient_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IAMClient_Whoami_Call) Return(uUID uuid.UUID, uUID1 uuid.UUID, err error) *IAMClient_Whoami_Call {
	_c.Call.Return(uUID, uUID1, err)
	return _c
}

func (_c *IAMClient_Whoami_Call) RunAndReturn(run func(ctx context.Context, sessionUUID uuid.UUID) (uuid.UUID, uuid.UUID, error)) *IAMClient_Whoami_Call {
	_c.Call.Return(run)
	return _c
}
