name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yml

  lint:
    name: "Lint"
    needs: build
    uses: ./.github/workflows/lint.yml

  test-api:
    name: "Test API"
    needs: build
    uses: ./.github/workflows/test-api.yml

  test-unit:
    name: "Test Unit"
    needs: build
    uses: ./.github/workflows/test-unit.yml

  test-e2e:
    name: "Test E2E"
    needs: build
    uses: ./.github/workflows/test-e2e.yml
